spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/skyrescue}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  environment: production

logging:
  level:
    root: INFO
    br.com.fiap.skyrescue: INFO
